Add miopen.lds_barrier operator with translation to gpu.lds_barrier to rocdl.lds_barrier
ROCm/rocMLIR pull request #118
Opened 2021-04-01 22:26 UTC by sjw36

Merged from miopen-dialect-index-diff-map branch

This feature allows generation of a barrier specific to LDS stores. It generates an asm implementation in the LLVMIR dialect with these instructions:

> s_waitcnt lgkmcnt(0)
> s_barrier

MLIR#120: https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/120

2021-04-01 22:44 UTC, whchung commented on mlir/test/Target/rocdl.mlir
> +// CHECK: target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A
we probably don't need these checks around datalayout and triple.

I'll be submitting another PR where we deliberately change width of pointers in generic address space to 32-bits so we tame the width of MLIR `index` type be the same as `i32` so avoid unnecessary integer upcast/downcast while doing GEP/load/store.

2021-04-01 22:45 UTC, whchung reviewed
thanks! one minor change in the unit test and this PR looks good to go.

2021-04-01 23:51 UTC, whchung commented
jenkins: retest this please.

@sjw36 let's disable flaky e2e tests should it persist.

2021-04-05 15:57 UTC, sjw36 commented
Yes, it also fails this way on TOT.

2021-04-05 16:17 UTC, whchung commented
@sjw36 got it. Let’s strike out those flaky fp16 tests.

2021-04-05 16:51 UTC, whchung requested changes
@sjw36 could we just strike out those flaky test configs, instead of killing the whole set?

2021-04-05 16:52 UTC, sjw36 commented
@whchung ok, let me narrow down.

2021-04-06 11:04 UTC, whchung approved these changes

2021-04-06 11:04 UTC, merged