Group convolution
ROCm/rocMLIR pull request #129
Opened 2021-04-12 07:06 UTC by asleepzzz

this PR enable group convolution,
padding and stride is ok
the format describe in mlir/docs/MIOpen/tensor_layout.md

we will test resnet101 f16 nhwc configs after f16 overflow issue fixed

2021-04-12 15:20 UTC, whchung requested changes
@asleepzzz / @ltqin In my first glance at the PR I don't see any e2e tests being added. Please help do that.

2021-04-12 15:22 UTC, whchung commented on mlir/test/mlir-miopen-driver/e2e/conv2d_host_validation_f16.mlir
> +// FIXME: mlir-miopen-driver -t f16 -pv -fil_layout=yxck -in_layout=nhwc -out_layout=nhwk -batchsize=128 -in_channels=8 -out_channels=128 -in_h=16 -in_w=16 -fil_h=3 -fil_w=3 --padding_h=1 --padding_w
@asleepzzz this config is passing on `miopen-dialect`. please help confirm if it has become FLAKY again, or it's just a missed piece in the rebase process.

2021-04-12 15:23 UTC, whchung commented on mlir/test/mlir-miopen-driver/e2e/conv2d_host_validation.mlir
> +// FIXME: mlir-miopen-driver -pv -fil_layout=kcyx -in_layout=nchw -out_layout=nkhw  -batchsize=64 -in_channels=4 -out_channels=64 -in_h=32 -in_w=32 -fil_h=1 -fil_w=1   --dilation_h=1 --dilation_w=1 -
@asleepzzz this config is passing on miopen-dialect. please help confirm if it has become incorrect again, or it's just a missed piece in the rebase process.

2021-04-12 15:27 UTC, whchung requested changes
It seems all logic related to `miopen.lds_barrier` is somehow missing in this PR, as well as some test configs related with flakiness in fp16. Please help fix them.

2021-04-12 15:27 UTC, whchung commented on mlir/test/Target/rocdl.mlir
> -llvm.func @rocdl.lds_barrier() {
@asleepzzz this test can *NOT* be removed.

2021-04-12 15:27 UTC, whchung commented on mlir/test/Target/rocdl.mlir
> -// CHECK: target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A
@asleepzzz this check can *NOT* be removed.

2021-04-12 15:27 UTC, whchung commented on mlir/test/Dialect/MIOpen/ops_2.mlir
> -func @miopen_lds_barrier() {
@asleepzzz this test can *NOT* be removed.

2021-04-12 15:27 UTC, whchung commented on mlir/test/Dialect/LLVMIR/rocdl.mlir
> -func @rocdl.lds_barrier() {
@asleepzzz this test can *NOT* be removed.

2021-04-12 15:27 UTC, whchung commented on mlir/test/Dialect/GPU/ops.mlir
> -      "gpu.lds_barrier"() : () -> ()
@asleepzzz this test can *NOT* be removed.

2021-04-12 15:27 UTC, whchung commented on mlir/test/Conversion/MIOpenToGPU/misc_ops.mlir
> -    // CHECK: gpu.lds_barrier
@asleepzzz this test can *NOT* be removed.

2021-04-12 15:27 UTC, whchung commented on mlir/test/Conversion/GPUToROCDL/gpu-to-rocdl.mlir
> -gpu.module @test_module {
@asleepzzz this test can *NOT* be removed.

2021-04-12 15:30 UTC, whchung commented
@ltqin / @asleepzzz After the first iteration of going over the PR, I can think of 2 places be improved:
1. add e2e tests . It is crucial from now on to let CI help us continue monitor the correctness of the implementation.
2. fix lost information in the rebase process. `miopen.lds_barrier` and some critical flakiness checks were left out.

2021-04-12 15:31 UTC, whchung commented
> this PR enable group convolution,
> padding and stride is ok
> the format describe in mlir/docs/MIOpen/tensor_layout.md
> 
> we will test resnet101 f16 nhwc configs after f16 overflow issue fixed

wondering have we tested resnext101 f32 nchw and nhwc cases with group > 1? I think they can be good candidates for e2e tests.

2021-04-12 15:40 UTC, yiqian1 commented on mlir/tools/mlir-miopen-driver/mlir-miopen-driver.cpp
> +  //  %g = constant 1: i8
This should be %g = constant 103: i8. It's the ascii of 'g'.

2021-04-12 15:54 UTC, yiqian1 commented on mlir/lib/ExecutionEngine/ROCm/rocm-runtime-wrappers.cpp
> +getSizesAndStrides(int64_t rank1, StridedMemRefType<float, 5> *filter,
This function is not needed anymore.

2021-04-12 15:59 UTC, yiqian1 commented on mlir/lib/ExecutionEngine/ROCm/rocm-runtime-wrappers.cpp
>  static void
This function is not needed because the internal representation would be always 5-dimensions, right?

2021-04-12 16:17 UTC, yiqian1 commented
And the two conv2d_harness_cpu_verifier* files under the e2e folder should be updated.

2021-04-12 16:19 UTC, whchung commented on mlir/tools/mlir-miopen-driver/mlir-miopen-driver.cpp
> +  //  %g = constant 103: i8
It may be a better idea to amend the comment to say we are emitting the ASCII codes for those letters.

2021-04-12 16:52 UTC, asleepzzz commented
> @ltqin / @asleepzzz After the first iteration of going over the PR, I can think of 2 places be improved:
> 
> 1. add e2e tests . It is crucial from now on to let CI help us continue monitor the correctness of the implementation.
> 2. fix lost information in the rebase process. `miopen.lds_barrier` and some critical flakiness checks were left out.

2. done
1. It's hard to add resnet101 configs due to padding =1, not all elements  has the same value,
for example:
./bin/mlir-miopen-driver -p=false -fil_layout=gkcyx -in_layout=gnchw -out_layout=gnkhw -groupsize=32 -batchsize=256 -in_channels=1024 -out_channels=1024 -in_h=14 -in_w=14 -fil_h=3 -fil_w=3 --dilation_h=1 --dilation_w=1 --padding_h=1 --padding_w=1 --conv_stride_h=2 --conv_stride_w=2 -pr -c -ph | ./bin/mlir-rocm-runner --shared-libs=./lib/librocm-runtime-wrappers.so,./lib/libmlir_runner_utils.so --entry-point-result=void

some results are 288 <=full ,some are 192 <=edge ,some are 128 <= corner

2021-04-12 16:54 UTC, asleepzzz commented
> @ltqin / @asleepzzz After the first iteration of going over the PR, I can think of 2 places be improved:
> 
> 1. add e2e tests . It is crucial from now on to let CI help us continue monitor the correctness of the implementation.
> 2. fix lost information in the rebase process. `miopen.lds_barrier` and some critical flakiness checks were left out.

2.done 
1. it's hard to add resnet101 configs, padding always >0 ,
for example
./bin/mlir-miopen-driver -p=false -fil_layout=gkcyx -in_layout=gnchw -out_layout=gnkhw -groupsize=32 -batchsize=256 -in_channels=1024 -out_channels=1024 -in_h=14 -in_w=14 -fil_h=3 -fil_w=3 --dilation_h=1 --dilation_w=1 --padding_h=1 --padding_w=1 --conv_stride_h=2 --conv_stride_w=2 -pr -c -ph | ./bin/mlir-rocm-runner --shared-libs=./lib/librocm-runtime-wrappers.so,./lib/libmlir_runner_utils.so --entry-point-result=void 
some results are
288<=in the center 192<= in the edge 128 <= corner

2021-04-13 05:50 UTC, asleepzzz commented
resnet101 configs already added in 
mlir/test/mlir-miopen-driver/e2e/conv2d_host_validation.mlir
mlir/test/mlir-miopen-driver/e2e/conv2d_host_validation_f16.mlir

2021-04-13 09:31 UTC, asleepzzz commented
driver can pass this test in  local but failed on ci
mlir-miopen-driver/cpu_conv2d/kyxc_nhwc_nhwk_bwd_data.mlir

mlir-miopen-driver -prc -fil_layout=kyxc -in_layout=nhwc -out_layout=nhwk  -batchsize=1 -in_channels=2 -out_channels=2 -in_h=6 -in_w=6 -fil_h=3 -fil_w=3 --dilation_h=2 --dilation_w=2 --padding_h=1 --padding_w=1 --conv_stride_h=2 --conv_stride_w=2 --operation=conv2d_bwd_data -p=false  -c | mlir-rocm-runner --shared-libs=/home/jenkins/workspace/MLIR/MLIR-downstream-unit-test/build/lib/librocm-runtime-wrappers.so,/home/jenkins/workspace/MLIR/MLIR-downstream-unit-test/build/lib/libmlir_runner_utils.so --entry-point-result=void | /home/jenkins/workspace/MLIR/MLIR-downstream-unit-test/build/bin/FileCheck /home/jenkins/workspace/MLIR/MLIR-downstream-unit-test/mlir/test/mlir-miopen-driver/cpu_conv2d/kyxc_nhwc_nhwk_bwd_data.mlir --check-prefix=CHECK16

2021-04-13 19:17 UTC, jerryyin commented
@whchung Can we hold off merging this PR until I have a MIOpen code review addressed? Once this PR is in, I will be forced to amend all existing MIOpen PRs since it changed the device interface.

@sjw36 for awareness.

2021-04-14 15:29 UTC, whchung commented
> @whchung Can we hold off merging this PR until I have a MIOpen code review addressed? Once this PR is in, I will be forced to amend all existing MIOpen PRs since it changed the device interface.

@jerryyin This PR is really big, and we are starting to cover some configs of resnext101. The more we wait the more rebase / cherry-pick @asleepzzz have to do and this holds off their next assignment, bwd v4r1.

I plan to take the PR after:
- @asleepzzz and @ltqin provide us a spreadsheet covering what's supported, and what's NOT supported in resnext101 configs.
- along with a list of remaining tasks to be done.

We shall address your concern in the weekly meeting today.

2021-04-14 17:36 UTC, asleepzzz commented
[Uploading resnet101_group_configs.xlsx…]()

2021-04-15 01:07 UTC, closed without merging