Add UnMerge and Slice  transform
ROCm/rocMLIR pull request #145
Opened 2021-04-16 13:28 UTC by ltqin

Add "UnMerge" and "Slice" transform to affine map, these will be used on backward data

2021-04-16 13:28 UTC, ROCm-Apps-Test commented
Can one of the admins verify this patch?

2021-04-16 13:29 UTC, whchung commented
jenkins: test this please.

2021-04-16 13:31 UTC, whchung commented on mlir/test/Dialect/MIOpen/lowering_affine_transform_slice.mlir
> +// CHECK: #map = affine_map<(d0, d1, d2) -> (d1 + 32, d2 + 64, d0)>
@asroy please help review if the math is correct.

2021-04-16 13:31 UTC, whchung commented on mlir/test/Dialect/MIOpen/lowering_affine_transform_unmerge.mlir
> +// CHECK_NEXT: #map3 = affine_map<(d0, d1, d2, d3) -> (d0, d2, (d1 * 8 + d3) floordiv 9, ((d1 * 8 + d3) mod 9) floordiv 3, ((d1 * 8 + d3) mod 9) mod 3)>
@asroy please help review if the math is correct.

2021-04-16 13:32 UTC, whchung commented
At the first glance it seems correct to me. I'll ask @asroy to do another round of review to ensure the affine transform for `slice` and `unmerge` is correct.

2021-04-16 14:26 UTC, whchung commented
@ltqin please fix `clang-format`.

2021-04-19 15:22 UTC, asroy requested changes

2021-04-19 15:22 UTC, asroy commented on mlir/test/Dialect/MIOpen/lowering_affine_transform_unmerge.mlir
> +    %1 = miopen.transform(%0) {gridwise_gemm_argument_position = 0 : i32, layout = [{dimensions = [0 : i32], names = ["gemmG"], source_dimensions = [0 : i32], source_names = ["gemmG"], transformation
```gemmK``` instead of ```gemmk```

2021-04-19 15:22 UTC, asroy commented on mlir/test/Dialect/MIOpen/lowering_affine_transform_unmerge.mlir
> +// CHECK_NEXT: #map3 = affine_map<(d0, d1, d2, d3) -> (d0, d2, (d1 * 8 + d3) floordiv 9, ((d1 * 8 + d3) mod 9) floordiv 3, ((d1 * 8 + d3) mod 9) mod 3)>
@ltqin can you add the expression in the code here as comment? It's hard to read the meaning of the maps.

Also please move these lines near the corresponding ```miopen_conv2d_x``` code

2021-04-19 15:26 UTC, whchung commented on mlir/test/Dialect/MIOpen/lowering_affine_transform_unmerge.mlir
> +// CHECK_NEXT: #map3 = affine_map<(d0, d1, d2, d3) -> (d0, d2, (d1 * 8 + d3) floordiv 9, ((d1 * 8 + d3) mod 9) floordiv 3, ((d1 * 8 + d3) mod 9) mod 3)>
@ltqin also please move `// CHECK` macros closer to its corresponding `miopen.transform` so it's easier to compare the input op versus output affine map.

2021-04-20 04:01 UTC, ltqin commented on mlir/test/Dialect/MIOpen/lowering_affine_transform_unmerge.mlir
> +    %1 = miopen.transform(%0) {gridwise_gemm_argument_position = 0 : i32, layout = [{dimensions = [0 : i32], names = ["gemmG"], source_dimensions = [0 : i32], source_names = ["gemmG"], transformation
Done. Rewrite the test unit

2021-04-20 04:11 UTC, ltqin commented
@asroy Yes, The attributes of "UnMerge"  are not clear to describe how to split dimension , and some content in unit test is not necessary. so I rewrite it. Again ,please see if the following is easy to understand

2021-04-20 05:00 UTC, asroy commented on mlir/test/Dialect/MIOpen/lowering_affine_transform_slice.mlir
> +  func @miopen_conv2d(%arg0: memref<160x192x3xf32>) {
call it ```miopen_slice_test``` maybe?

2021-04-20 05:00 UTC, asroy approved these changes

2021-04-20 11:08 UTC, merged