Fix a bug when using atomicFadd in the fp16 scalar case
ROCm/rocMLIR pull request #1458
Opened 2024-03-15 18:52 UTC by giuseros

So there was a simple bug to fix, but the main issue was that we were not always selecting the atomicFadd intrinsic when doing an atomic Fp16/Fp32 addition (that's why I didn't catch the bug before). 

I enabled the buffer operation (i.e., the intrinsics) for all the atomics Fp16/Fp32 cases. @krzysz00 can you take a look? Is there a reason why we were not always enabling the intrinsic?

FYI, using atomics I always see accuracy degradation. 

```
./bin/rocmlir-gen --arch gfx90a -pv   --operation gemm -t f16 -g 1 -m 256 -k 512 -n 256  --perf_config 64,64,16,32,32,4,1,1,1 -split-k 2 | ./bin/rocmlir-driver -c | ../mlir/utils/widgets/rocm-run 
Number of elements: 65536
maxAbsDiff info: maxAbsDiff = 0.250000 (valNum = 309.50000, gpuNum = 309.25000), average absDiff = 5.6e-02
maxRelDiff info: maxRelDiff = 8.1e-04 (valNum = 309.5000000000, gpuNum = 309.2500000000), average relDiff = 1.8e-04
RMS = 3.8e-04
Histogram of relDiff: 
        relDiff = 0     : 50915/65536 (77.690125%)
     0 < relDiff < 1e-06: 0/65536 (0.000000%)
1e-06 < relDiff <= 1e-05: 0/65536 (0.000000%)
1e-05 < relDiff <= 1e-04: 0/65536 (0.000000%)
1e-04 < relDiff <= 1e-03: 14621/65536 (22.309875%)
1e-03 < relDiff <= 1e-02: 0/65536 (0.000000%)
1e-02 < relDiff <= 1e-01: 0/65536 (0.000000%)
1e-01 < relDiff <= 1e+00: 0/65536 (0.000000%)
1e+00 < relDiff < inf   : 0/65536 (0.000000%)
        relDiff = inf   : 0/65536 (0.000000%)
[0 1 1]
```
This happens with the CAS loop and with the atomic intrinsics.

2024-03-15 18:53 UTC, giuseros commented
@ravil-mobile this should get you going with split-k tests. Again, you will have to adjust the accuracy, because atomics are less accurate (so split-k will be less accurate). Maybe another reason to do locks?

2024-03-15 19:01 UTC, sjw36 commented
An atomic reduction (accumulation in fp16) will generally result in less accuracy vs a full mfma reduction (accumulation in at least f32).

2024-03-15 19:08 UTC, sjw36 commented
What is the accuracy degradation on f32?

2024-03-15 19:17 UTC, sjw36 approved these changes
Looks good overall, just 1 question.

2024-03-15 19:17 UTC, sjw36 commented on mlir/lib/Dialect/Rock/Transforms/SugarToLoops.cpp
> +    bool isAtomicFadd = memoryOp == StoreMethod::AtomicAdd && elemTy.isF16();
should this also allow f32?

2024-03-18 08:48 UTC, ravil-mobile commented
Hi @giuseros, I tried you patch and it works.

2024-03-18 09:19 UTC, giuseros commented
Hi @sjw36 , 
You are right, in the parallel data path we always accumulate in fp32. Indeed fp32 atomics work ok.

2024-03-18 14:58 UTC, krzysz00 requested changes
1. We should be using global operations instead of buffer operations when possible, since they don't incur bounds checks
2. If that atomic is lowering to a CAS loop, try setting `"amdgpu-unsafe-fp-atomics"="true"` on the way to LLVM.
3. (If it isn't, we might as well always go to a buffer)

2024-03-18 16:05 UTC, giuseros commented
> 1. We should be using global operations instead of buffer operations when possible, since they don't incur bounds checks
> 2. If that atomic is lowering to a CAS loop, try setting `"amdgpu-unsafe-fp-atomics"="true"` on the way to LLVM.
> 3. (If it isn't, we might as well always go to a buffer)

Alright, I see what you mean. However, I don't see any difference performance-wise between global and buffer atomics. That said, let's agree on the logic. 

For fp16, I always need to write packed vectors (using the intrinsic). Does `atomic_rmw` supports vectors? If yes, the logic can be `use atomic_rmw everytime you don't need buffer checks, sue buffer ops otherwise (+enable unsafe-fp-atomics).` If  `atomic_rmw` does not support vectors, we need to use that logic only for fp32, and let fp16 always use the buffer intrinsics.

2024-03-18 18:30 UTC, krzysz00 commented
@giuseros For the vector case, you'll want `amdgcn_global_atomic_fadd` - it's an intrinsic you'll need to add `amdgpu` wrappers for, probably.

2024-03-18 18:30 UTC, krzysz00 commented
Or least I'd expect that to be what you want there.

2024-03-21 01:09 UTC, giuseros commented
So, ok, adding `amdgcn_global_atomic_fadd` seems a bit too much for this PR, that wanted mostly to address a bug. We need to pipe it through `AMDGPUDialect` and then add it in ROCDL. I agree that this is what we should be doing, and I left a TODO in the code. Given that performance are very similar for now I would use buffer atomics whenever there is a fp16 (packed or unpacked).

2024-03-21 10:02 UTC, ravil-mobile commented
> So, ok, adding `amdgcn_global_atomic_fadd` seems a bit too much for this PR, that wanted mostly to address a bug. We need to pipe it through `AMDGPUDialect` and then add it in ROCDL. I agree that this is what we should be doing, and I left a TODO in the code. Given that performance are very similar for now I would use buffer atomics whenever there is a fp16 (packed or unpacked).

Maybe you can also immediately fire a ticket which with the TODO description?

2024-03-21 16:01 UTC, krzysz00 reviewed
Agreed that we can do the global packed atomic in the future since it's not that big of a deal. It looks like this still needs flattening?

2024-03-21 16:01 UTC, krzysz00 commented on external/llvm-project/mlir/lib/Target/LLVMIR/Dialect/ROCDL/ROCDLToLLVMIRTranslation.cpp
> +      attrValueStream << "true";
Note: Let's make the attribute an actual boolean

2024-03-21 16:01 UTC, krzysz00 commented on mlir/lib/Conversion/RockToGPU/RockToGPU.cpp
> +        gpuFunc->setAttr("rocdl.unsafe_fp_atomics", b.getUnitAttr());
I'd just set it unconditionally

2024-03-22 09:29 UTC, giuseros commented
> Maybe you can also immediately fire a ticket which with the TODO description?
Done: https://github.com/ROCm/rocMLIR-internal/issues/1429

2024-03-22 15:20 UTC, krzysz00 approved these changes
Approved modulo maybe we should have some tests for the atomic add logic

2024-03-22 18:28 UTC, giuseros commented
> Approved modulo maybe we should have some tests for the atomic add logic
I added additional two tests to stress the flattening logic

2024-03-23 16:58 UTC, merged