Add support for update.dpp intrinsic
ROCm/rocMLIR pull request #1493
Opened 2024-04-24 15:15 UTC by stefankoncarevic

"Extended the DPP operation to support the optional 'old' operandand the update.dpp intrinsic. Implemented and ensured 'old' defaults to 'src' when not provided. This allows the use of update.dpp in all cases, effectively behaving like mov.dpp when lowering in backend."

2024-04-24 15:18 UTC, stefankoncarevic commented on external/llvm-project/mlir/include/mlir/Dialect/LLVMIR/ROCDLOps.td
I was guided by this
https://github.com/llvm/llvm-project/blob/c1086532d4d5c0a261457dfb00e79fcb764e3d78/llvm/lib/Target/AMDGPU/VOP1Instructions.td#L1339
to only use update dpp.

2024-04-25 22:07 UTC, krzysz00 requested changes
I'd like to see evidence of this alleged deprecation

2024-04-25 22:07 UTC, krzysz00 commented on external/llvm-project/mlir/include/mlir/Dialect/AMDGPU/IR/AMDGPU.td
> +    $src (`(` $old^ `:` type($old) `)`)? $kind (`(` $permArgument^ `)`)? attr-dict `:` type($result)
```
src (`,'^ $old)?
```

Also, if you wait for upstream merge to land first, you'll get access to `OptionalTypesMatchWith`, so you don't have to repeat the type.

2024-04-25 22:07 UTC, krzysz00 commented on external/llvm-project/mlir/include/mlir/Dialect/LLVMIR/ROCDLOps.td
... that's not what that says.

That's two rewrite patterns.

Can you please point me to some specific indication that the mov.dpp intrinsic shouldn't be used?

2024-05-08 14:05 UTC, stefankoncarevic commented
> I'd like to see evidence of this alleged deprecation

On this link https://github.com/llvm/llvm-project/pull/89233
from the upstream ticket there is a comment from Matt, that mov dpp is deprecated intrinsic, and should be replaced with update.dpp.
The link I posted above in the comment only gives an insight into how mov.dpp can be replaced with update.dpp to behave the same. As for me, I can separate in ROCDLOps.td that we have both mov.dpp and update.dpp so that we can choose which one we want to use.

2024-05-08 15:14 UTC, krzysz00 reviewed
Per comments upstream, let's do what Matt said and always have an `old` argument and always use `update_dpp`.

However, while you're doing that, can you add some stuff to the documentation on mov.dpp - either in the LLVM documentation or in comments in `IntrinsicsAMDGPU.td` and maybe a deprecation on the builtin in clang? That'll be a separate commit but let's keep it in the same PR here.

2024-05-10 14:48 UTC, krzysz00 approved these changes
Approved!

2024-05-21 09:57 UTC, merged