Make tuning-driver get arch from func or mod
ROCm/rocMLIR pull request #1518
Opened 2024-05-16 11:00 UTC by manupak

Currently, the tuning-driver has a requirement
that the module needs to have the arch.
However, our clients may only set the arch
in the func.

This commit adds support to get get arch from
func or mod before failing the tuning-driver.

2024-05-17 16:05 UTC, krzysz00 approved these changes
Seems reasonable to me.

2024-05-17 16:07 UTC, krzysz00 requested changes
I don't think this is an accurate description of the changes: this now only gets `arch` from functions.

Can you keep the original logic?

That is,

1. If `mhal.arch` is set on the module, use that, otherwise
2. Walk the modules's functions to find an `mhal.arch`

2024-05-17 16:10 UTC, manupak commented
> If mhal.arch is set on the module, use that, otherwise
Walk the modules's functions to find an mhal.arch

Why does module arch take precedence ? 
or better yet do we even support if there is a mismatch ?

2024-05-17 16:14 UTC, manupak commented
Also does tuning-driver support multi-kernel in single module scenario ?

2024-05-17 16:26 UTC, manupak commented
>  this now only gets arch from functions.

no, this gets from func, if not module.
func takes precedence but also assumes there is one kernel func per module. hence the previous question

2024-05-20 14:39 UTC, krzysz00 commented
@manupak  Yeah, multiple kernels in one module is supported, see backwards data.

And I'd want module arch taking precedence because it's easier to get to.

2024-05-23 09:51 UTC, manupak commented
>  I'd want module arch taking precedence because it's easier to get to.

FYI, This is not how we have been doing in the rest of the code base. See https://github.com/ROCm/rocMLIR/pull/1439/files#diff-f03bc66ec82c54629193060fb61d5427604f0f9842eeafe2d18ac9b08ad56aeb (even before my changes on 1439). and I d like it done same way thoughout the codebase. Practically, we never encountered a case where there was a conflict rather we encounter where one is missing (func vs module). 

To be clear, Im not opposing module taking preference; I just want to make sure we do it same throughout.
"because it's easier to get to" is not a good reason; here alternative is not that hard.

2024-05-28 14:43 UTC, krzysz00 approved these changes
Yeah, I see your point, approved

2024-06-27 10:02 UTC, merged