[EXTERNAL] Add amdgpu.sched_barrier
ROCm/rocMLIR pull request #1569
Opened 2024-07-15 13:37 UTC by manupak

This commit adds sched_barrier operator
to AMDGPU dialect that lowers to rocdl.sched.barrier.

2024-07-15 13:37 UTC, manupak commented
(I ll create the upstream PR shortly)

2024-07-15 15:10 UTC, krzysz00 requested changes
I think your enum could use the facilities for bitwise enums

2024-07-15 15:10 UTC, krzysz00 commented on external/llvm-project/mlir/include/mlir/Dialect/AMDGPU/IR/AMDGPU.td
> +  let summary = "Barrier that includes a wait for LDS memory operations.";
Copy-paste-o

2024-07-15 15:10 UTC, krzysz00 commented on external/llvm-project/mlir/lib/Conversion/AMDGPUToROCDL/AMDGPUToROCDL.cpp
> +    for (Attribute opt : op.getOpts()) {
You may not need the for loop here - you could get the attribute and `static_cast` it?

2024-07-15 15:10 UTC, krzysz00 commented on external/llvm-project/mlir/include/mlir/Dialect/AMDGPU/IR/AMDGPU.td
> +def AMDGPU_SchedBarrierOpOptArrayAttr : TypedArrayAttrBase<AMDGPU_SchedBarrierOpOptAttr,
Instead of doing this, use the bitwise enum attr

2024-07-15 15:16 UTC, manupak commented
Thanks @krzysz00. 
I ve realized that now. (thanks to @antiagainst).
I ve addressed those here : https://github.com/llvm/llvm-project/pull/98911/files. 
Shall we review that first ? and I ll backport it here.

2024-08-01 12:52 UTC, manupak commented
supersceded by : https://github.com/ROCm/rocMLIR/pull/1595

2024-08-01 12:52 UTC, closed without merging