right padding
ROCm/rocMLIR pull request #180
Opened 2021-05-04 17:49 UTC by asleepzzz

this PR support leftpad=0 rightpad>0

2021-05-04 18:00 UTC, whchung commented on mlir/lib/Dialect/MIOpen/Transforms/AffineTransforms.cpp
> +        // parameters.getValue()[0].dyn_cast<IntegerAttr>().getInt();
please remove unused code.

2021-05-04 18:02 UTC, whchung commented on mlir/lib/Dialect/MIOpen/Transforms/AffineTransforms.cpp
> +          // [0, 2, 3, 1] leftpadH = 0 rightPadH = 2 leftpadW = 3 rightPadW = 1
this paragraph better be re-formatted to say it's an example, otherwise it's hard to understand what `[0, 2, 3, 1]` means.

2021-05-04 18:02 UTC, whchung requested changes
please help revise comments.

2021-05-06 05:12 UTC, whchung commented on mlir/include/mlir/Dialect/MIOpen/AffineMapHelper.h
> +
Do we also need to check the RHS?

if yes, the codes need to be revised
If no, perhaps a comment is needed to document why the RHS doesn’t need such a check

2021-05-06 18:01 UTC, whchung requested changes
Right padding values are still computed, not manually specifiable.

2021-05-06 18:01 UTC, whchung commented on mlir/include/mlir/Dialect/MIOpen/LowerMIOpenOps.h
> +                                     b.getI32IntegerAttr(rightPadH),
There seems to be no flags in `mlir-miopen-driver` to allow users manually specify `rightPadH` and `rightPadW`, and thus these 2 values are still computed based on `padding_h` and `padding_w`.

2021-05-07 04:37 UTC, asleepzzz commented on mlir/include/mlir/Dialect/MIOpen/LowerMIOpenOps.h
> +                                     b.getI32IntegerAttr(rightPadH),
I can pass it , but may I change 
    auto hiPadded = 1 + (y - 1) * dilationH + (ho - 1) * strideH;
    auto wiPadded = 1 + (x - 1) * dilationW + (wo - 1) * strideW;
to
    auto hiPadded = hi+rightpad+leftpad
    auto wiPadded = wi+rightpad+leftpad

2021-05-07 14:04 UTC, whchung commented on mlir/tools/mlir-miopen-driver/mlir-miopen-driver.cpp
> +    if (paddingHeightLeft.getValue() == 0 &&
better to leave comment here to specify `padding_h` supersedes `padding_h_l` and `padding_h_r`. same goes with `padding_w`.

2021-05-07 14:04 UTC, whchung requested changes
@asleepzzz We are very close to get this PR merged. Just some minor tweaks in the commnts.

2021-05-07 14:20 UTC, whchung approved these changes
LGTM

2021-05-07 14:58 UTC, merged

2021-05-11 14:24 UTC, whchung commented
This PR is causing many regressions in the e2e nightly CI and will be reverted.