Add MIOpenDriver Xdlop tests
ROCm/rocMLIR pull request #207
Opened 2021-05-12 20:55 UTC by yiqian1

2021-05-12 21:05 UTC, jerryyin approved these changes
Changes LGTM. If all CI pass + this `miopen-test` CI pass, please merge yourself.

2021-05-12 21:11 UTC, jerryyin requested changes
Please investigate why CI pass with wrong solver name, [here](http://10.236.106.97:8080/job/MLIR-MIOpen-test/50/console).

2021-05-12 21:11 UTC, jerryyin commented on mlir/utils/jenkins/miopen-tests/resnet50_fp16_nhwc_xdlop.sh
> +export MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvMlirIgemmFwdXdlop
Xdlops

2021-05-12 21:11 UTC, jerryyin commented on mlir/utils/jenkins/miopen-tests/resnet50_fp16_nhwc_xdlop.sh
> +export MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvMlirIgemmWrWXdlop
Xdlops

2021-05-12 21:11 UTC, jerryyin commented on mlir/utils/jenkins/miopen-tests/resnet50_fp32_nchw_xdlop.sh
> +export MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvMlirIgemmFwdXdlop
Xdlops

2021-05-12 21:11 UTC, jerryyin commented on mlir/utils/jenkins/miopen-tests/resnet50_fp32_nchw_xdlop.sh
> +export MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvMlirIgemmWrWXdlop
Xdlops

2021-05-12 21:11 UTC, jerryyin commented on mlir/utils/jenkins/miopen-tests/resnet50_fp32_nhwc_xdlop.sh
> +export MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvMlirIgemmFwdXdlop
Xdlops

2021-05-12 21:11 UTC, jerryyin commented on mlir/utils/jenkins/miopen-tests/resnet50_fp32_nhwc_xdlop.sh
> +export MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvMlirIgemmWrWXdlop
Xdlops

2021-05-13 15:02 UTC, yiqian1 commented
The problem was I ran the shell scripts in the background and wait for all background jobs to finish. The background jobs continued even when one of tests failed and returned the status of the last executed process. I've changed the scripts to 

1) stop the script if one of background processes fails; 
2) count the number of successful tests and return exit code of 1 if one of tests fails.

2021-05-13 15:30 UTC, jerryyin approved these changes
LGTM. Thanks for helping triage && update the bash script such that test can work in parallel.  Please remember to make Jenkinsfile point back to `miopen-dialect` branch when this is merged.

2021-05-13 15:30 UTC, merged