enable raw buffer store, so we can do oob store
ROCm/rocMLIR pull request #248
Opened 2021-06-02 11:07 UTC by asleepzzz

this PR enable oob store for 
fp32,fp16 in xdlop, non xdlops

bf16 only in xdlops due to we do not have non xdlop bf16 support

2021-06-02 13:42 UTC, whchung commented on mlir/include/mlir/Dialect/MIOpen/LowerMIOpenOps.h
> +          // bf16 rsults not correct when in_h & in_w odd
Add FIXME for bf16

2021-06-02 13:44 UTC, whchung requested changes
Add a new unit test as we introduce a new op in this PR

2021-06-02 13:57 UTC, whchung commented on mlir/lib/Conversion/GPUToROCDL/LowerGpuOpsToROCDLOps.cpp
> +      } else { // f16 and i16 (bf16) types scalar value
add FIXME

2021-06-02 13:58 UTC, whchung commented on mlir/lib/Conversion/GPUToROCDL/LowerGpuOpsToROCDLOps.cpp
> +
nit: don't need this newline

2021-06-02 14:00 UTC, whchung commented on mlir/include/mlir/Dialect/MIOpen/LowerMIOpenOps.h
> +        if (toEmitOOBStoreCheckLogic) {
the comment above needs to be fixed.

2021-06-02 14:00 UTC, whchung commented on mlir/include/mlir/Dialect/MIOpen/LowerMIOpenOps.h
> +      if (toEmitOOBStoreCheckLogic) {
the comment above needs to be fixed.

2021-06-02 14:00 UTC, whchung commented on mlir/include/mlir/Dialect/MIOpen/LowerMIOpenOps.h
> +          // bf16 rsults not correct when in_h & in_w odd
add FIXME.

2021-06-02 14:02 UTC, sjw36 approved these changes
functionality looks good. minor comment cleanup.

2021-06-02 14:02 UTC, sjw36 commented on mlir/lib/Conversion/GPUToROCDL/LowerGpuOpsToROCDLOps.cpp
> +
remove newline.

2021-06-02 14:02 UTC, sjw36 commented on mlir/lib/Conversion/GPUToROCDL/LowerGpuOpsToROCDLOps.cpp
> +    // word 2: fixed as -1 .
comment doesn't match logic (-1 vs 2)

2021-06-03 04:58 UTC, whchung approved these changes

2021-06-03 13:34 UTC, whchung commented
jenkins: retest this please

2021-06-03 15:47 UTC, whchung commented
jenkins: retest this please.

2021-06-03 22:51 UTC, whchung commented
jenkins: retest this please.

2021-06-05 00:36 UTC, merged

2021-07-09 18:32 UTC, whchung commented on mlir/test/Conversion/GPUToROCDL/rawbuf_store.mlir
> +    gpu.buffer_store(%value, %dst, %shift, %offset0) : f32, memref<128xf32>, i32
turns out we are NOT really testing `gpu.raw_buffer_store` and `rocdl.raw.buffer.store` . We are considered lucky that the whole thing works.