fix backward data issue
ROCm/rocMLIR pull request #307
Opened 2021-07-14 05:41 UTC by asleepzzz

this PR fix backward data stride=2 issues
 ./bin/mlir-miopen-driver -pv -c -fil_layout=gkcyx -in_layout=ngchw -out_layout=ngkhw -groupsize=1 -batchsize=64 --padding_h=1 --padding_w=1 -in_channels=64 -out_channels=64 -in_h=51 -in_w=51 -fil_h=3 -fil_w=3 -p=false   --conv_stride_h=2   --conv_stride_w=2  --operation=conv2d_bwd_data  |./bin/mlir-rocm-runner --shared-libs=./lib/librocm-runtime-wrappers.so,./lib/libmlir_runner_utils.so --entry-point-result=void

sometimes the htilda >hout  or wtilda >wout
is this cases we need to add out of boundary check

2021-07-14 21:05 UTC, whchung requested changes
The comments need more work.

2021-07-14 21:05 UTC, whchung commented on mlir/tools/mlir-miopen-driver/mlir-miopen-driver.cpp
> +                         int rightPadLen, int strideLen, int dilLen) {
Comment is needed here to describe the logic

2021-07-14 21:05 UTC, whchung commented on mlir/tools/mlir-miopen-driver/mlir-miopen-driver.cpp
> +  paddingWidthRight.setValue(in_right_pad_w);
A large amount of non-trivial logic were introduced without comment.

2021-07-14 21:05 UTC, whchung commented on mlir/include/mlir/Dialect/MIOpen/LowerMIOpenOps.h
> +          // but this logic(wTildaSlice > wo) is correct
This comment can’t be understood easily. Please try rephrase it.

it seems you are stating something is wrong but the logic is correct?

2021-07-15 09:01 UTC, asleepzzz commented
this config can trigger bwd failed:

./bin/mlir-miopen-driver -pv -c -fil_layout=gkcyx -in_layout=ngchw -out_layout=ngkhw -groupsize=1 -batchsize=64 --padding_h=0 --padding_w=1 -in_channels=64 -out_channels=64 -in_h=4 -in_w=7 -fil_h=1 -fil_w=3   -p=false   --conv_stride_h=1   --conv_stride_w=2  --operation=conv2d_bwd_data  |./bin/mlir-rocm-runner --shared-libs=./lib/librocm-runtime-wrappers.so,./lib/libmlir_runner_utils.so --entry-point-result=void


it's not hw checking problem and this problem may the root cause of padding kernel fail

2021-07-19 13:44 UTC, whchung commented
@asleepzzz ping? I don't see anything being changed since I made my comments 5 days ago. Is this PR still relevant?

2021-07-20 15:29 UTC, whchung approved these changes

2021-07-20 17:31 UTC, merged