Merging MIGraphX ops dialect
ROCm/rocMLIR pull request #362
Opened 2021-08-27 08:49 UTC by jungpark-mlir

2021-08-27 14:22 UTC, sjw36 requested changes
Overall looks good. Just minor cleanup.
But it looks like some test files were moved out of external/llvm-project. We should keep the llvm code-base as clean and intact as possible. Please keep our capi tests separate and distinct.

2021-08-27 14:22 UTC, sjw36 commented on mlir/test/CAPI/ir.c
> +#include "mlir-c/Dialect/MIGraphX.h"
Is there a reason this was moved and not just copied, adding your code and removing other capi's?

2021-08-27 14:22 UTC, sjw36 commented on mlir/lib/Dialect/MIGraphX/CMakeLists.txt
> +# Configure ROCm support.
remove comments

2021-08-27 14:22 UTC, sjw36 commented on mlir/lib/Dialect/MIGraphX/MIGraphXOps.cpp
> +//===----------------------------------------------------------------------===//
remove unused unnamed namespace

2021-08-27 14:46 UTC, jungpark-mlir commented on mlir/test/CAPI/ir.c
> +#include "mlir-c/Dialect/MIGraphX.h"
Right, I was bit confused. I'll make a separate test

2021-08-27 21:10 UTC, sjw36 commented on mlir/include/mlir/Dialect/MIGraphX/MIGraphXOps.td
> +    Add two tensors elementwise
maybe reference the file in migraphx that corresponds to this operation type.

2021-08-27 21:13 UTC, sjw36 requested changes

2021-08-27 21:13 UTC, sjw36 commented on mlir/include/mlir/Dialect/MIGraphX/LowerMIGraphXOps.h
> +// Part of the MLIR Project, under the Apache License v2.0 with LLVM Exceptions.
I would like to get away from the Lower*Ops.h that has code in it. For this commit we don't have any lowering steps so let's just leave this out.

2021-08-27 21:53 UTC, jungpark-mlir commented on mlir/include/mlir/Dialect/MIGraphX/LowerMIGraphXOps.h
> +// Part of the MLIR Project, under the Apache License v2.0 with LLVM Exceptions.
True, got removed.

2021-08-30 14:59 UTC, sjw36 approved these changes

2021-08-31 15:06 UTC, merged