Add a full-model Resnet50 test
ROCm/rocMLIR pull request #444
Opened 2021-11-11 23:09 UTC by pcf000

A python script uses Tensorflow's Keras to make a model with a single fixed
image, then uses recent TF enhancements to generate TOSA MLIR to stdout,
whence it is piped to mlir-opt and mlir-cpu-runner. to verify the result.

Requires tf-nightly >= 2.8.0-dev20211102, which in turn requires python
3.7.  Adds those items to the rocm/mlir Dockerfile.  Marks the test as
unsupported if they aren't available.

2021-11-11 23:10 UTC, pcf000 commented on mlir/test/e2e/Inputs/resnet50-test.py
> +# wget https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Red_Smooth_Saluki.jpg/590px-Red_Smooth_Saluki.jpg
Where the image file I'm using came from.  It's included in the commit.

2021-11-12 17:59 UTC, krzysz00 requested changes
Thanks for putting in the work on this!

I'm requesting changes because I don't like how we're checking for Python version, but there might be some more significant issues with how this is structured that other folks can comment on.

2021-11-12 17:59 UTC, krzysz00 commented on mlir/test/e2e/lit.local.cfg
> +if not shutil.which('python3.7') or not importlib.util.find_spec('tensorflow'):
Let's not have a hard dependency on 3.7 - check the python version this configuration is being run in instead

2021-11-12 17:59 UTC, krzysz00 commented on mlir/test/e2e/resnet50-tosa-partition.mlir
> +// RUN: | mlir-opt --tosa-partition-pipeline --tosa-to-linalg-on-tensors --tosa-to-standard \
Sanity check: is this `mlir-opt` or `miopen-opt` (that is, have we been adding the tosa partitioning stuff to our directory or to external/)?

2021-11-12 17:59 UTC, krzysz00 commented on mlir/utils/jenkins/Dockerfile.rocm
> +        python3.7 python3.7-venv \
If we're doing this, might as well go to 3.9?

2021-11-12 17:59 UTC, krzysz00 commented on mlir/test/e2e/resnet50-tosa-partition.mlir
> +// RUN: | mlir-opt --tosa-partition-pipeline --tosa-to-linalg-on-tensors --tosa-to-standard \
More significantly, per @whchung , generating test inputs at test-time is generally considered not good in LLVM - see https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/miopen-dialect/mlir/utils/generateInWarpTransposeTest.py and https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/blob/miopen-dialect/mlir/test/Dialect/MIOpen/integration/in_warp_transpose/in_warp_transpose.mlir

Could this test be reworked to generate the MLIR offline and then to run that through the pipeline during testing? This has the advantage of letting us test the partitioning pass as well as the full end-to-end setup.

2021-11-17 21:15 UTC, krzysz00 commented on mlir/utils/jenkins/Dockerfile.rocm
> +    && rm -f /usr/bin/python3 && ln -s /usr/bin/python3.7 /usr/bin/python3 \
`update-alternatives`, please?

2022-09-21 17:45 UTC, pcf000 commented
This guy's been hanging around unresolved forever.  Closing because the world has changed around it, and we'll likely have something analogous soon, but with torch-mlir and less trouble.

2022-09-21 17:45 UTC, closed without merging