support bf16
ROCm/rocMLIR pull request #45
Opened 2021-01-14 09:47 UTC by asleepzzz

we modify driver to rocdl and support bf16,
but we do not yet implement host transform value to bf16

there are still so many unit tests we not modify(mfma bf16 already changed ,so unit tests must changed),
ex:
Conversion/GPUToROCDL/gpu-to-rocdl.mlir
Conversion/MIOpenToGPU/mfma_v2.mlir
Dialect/GPU/ops.mlir
Dialect/MIOpen/ops_2.mlir

2021-01-14 09:47 UTC, ROCm-Apps-Test commented
Can one of the admins verify this patch?

2021-01-15 05:49 UTC, asleepzzz commented
> Can one of the admins verify this patch?

 this PR is still in progress ,I can Letao finish most part of bf16 task, but there are still some 
verification not complete

2021-01-18 15:45 UTC, whchung commented
waiting for one end-to-end (compile + execution) example.

2021-01-20 05:50 UTC, asleepzzz commented
run:
./bin/mlir-miopen-driver -p -x2 -t bf16 -ph -c| ./bin/mlir-rocm-runner --shared-libs=./lib/librocm-runtime-wrappers.so,./lib/libmlir_runner_utils.so --entry-point-result=void
but verification not complete yet

2021-01-21 16:09 UTC, jerryyin commented
@asleepzzz Could you register a user in our CI site at http://ml-ci.amd.com:21096/? Once I got your user id, I will add you to the admin list such that your PR will trigger a CI run.

2021-01-25 20:50 UTC, asleepzzz commented
> @asleepzzz Could you register a user in our CI site at http://ml-ci.amd.com:21096/? Once I got your user id, I will add you to the admin list such that your PR will trigger a CI run.

name:hanchang
account:asleepzzz

2021-01-25 20:55 UTC, jerryyin commented
jenkins retest this please

2021-02-03 15:06 UTC, whchung requested changes
some minor changes are needed.
also fix help fix errors found in CI

2021-02-03 15:06 UTC, whchung commented on mlir/include/mlir/Dialect/MIOpen/LowerMIOpenOps.h
>        } else if (dataType == b.getF16Type() || dataType == b.getBF16Type()) {
remove `b.getBF16Type()` check.

2021-02-03 15:06 UTC, whchung commented on mlir/include/mlir/Dialect/MIOpen/LowerMIOpenOps.h
>      } else if (dataType == b.getF16Type() || dataType == b.getBF16Type()) {
remove `b.getBF16Type()` check.

2021-02-03 15:06 UTC, whchung commented on mlir/include/mlir/Dialect/MIOpen/LowerMIOpenOps.h
>        } else if (dataType == b.getF16Type() || dataType == b.getBF16Type()) {
remove b.getBF16Type() check.

2021-02-03 15:06 UTC, whchung commented on mlir/tools/mlir-miopen-driver/mlir-miopen-driver.cpp
> +static FuncOp createVerifyKevinFuncOp(ModuleOp &module, OpBuilder &builder,
the naming of the function is confusing. please revise it.

2021-02-03 15:06 UTC, whchung commented on mlir/tools/mlir-miopen-driver/mlir-miopen-driver.cpp
> +static FuncOp createVerifyKevinFuncOp(ModuleOp &module, OpBuilder &builder,
it seems the function is not used anywhere. please remove it if that's really the case.

2021-02-03 15:06 UTC, whchung commented
and please help resolve merge conflicts

2021-02-04 02:20 UTC, whchung commented
will hold off merging this PR until #53 gets merged.

2021-02-23 17:42 UTC, whchung commented
@asleepzzz / @ltqin please help rebase the PR to `miopen-dialect`, we have migrated to using a newer LLVM.

2021-03-11 12:08 UTC, closed without merging