Support int8 in the test generator miopen-gen
ROCm/rocMLIR pull request #521
Opened 2022-02-17 16:01 UTC by yiqian1

Generate int8 E2E test cases.

2022-02-17 17:26 UTC, krzysz00 commented
This is a note that CI is passing and that Thursday the 17th includes merges of unrelated fix PRs. Therefore, on approval, we can cheat the CI (manually kick off a build that unchecks sharedLib and staticLib)

2022-02-17 19:49 UTC, sjw36 commented on mlir/lib/Dialect/MIOpen/Generator/Conv2dGenerator.cpp
> +                                                  {"i8", 1}};
should use sizeof for all these even tho it is obvious

2022-02-17 20:04 UTC, yiqian1 commented on mlir/lib/Dialect/MIOpen/Generator/Conv2dGenerator.cpp
> +                                                  {"i8", 1}};
Should we use sizeof(uint16_t) for f16?

2022-02-17 20:31 UTC, sjw36 commented on mlir/lib/ExecutionEngine/ROCm/rocm-runtime-wrappers.cpp
> +                   int64_t stride2, int64_t stride3, int64_t stride4) {
This is fine for now but we should probably just have a single alloc func and insert casts from it.

2022-02-17 20:31 UTC, sjw36 commented on mlir/lib/ExecutionEngine/ROCm/rocm-runtime-wrappers.cpp
> +                   int64_t stride2, int64_t stride3, int64_t stride4) {
@yiqian1 can you file a ticket for that. thx

2022-02-17 20:33 UTC, sjw36 approved these changes
Looks good. Maybe some follow-up cleanup tickets.

2022-02-17 20:35 UTC, krzysz00 commented on mlir/lib/ExecutionEngine/ROCm/rocm-runtime-wrappers.cpp
> +                   int64_t stride2, int64_t stride3, int64_t stride4) {
I think y'all might want to look at what's been done upstream here as well - last I checked they've got a lot of these allocation functions templated in interesting ways.

2022-02-17 20:35 UTC, jerryyin commented on mlir/lib/Dialect/MIOpen/Generator/Conv2dGenerator.cpp
> +  }
Irrelevant to where I put the review...

I'd prefer a small end-to-end test (one of all 1, another of all 0s, for example) that exercise i8 convolution and get expected result by just using `miopen-gen`.

2022-02-17 20:38 UTC, krzysz00 commented on mlir/tools/miopen-gen/miopen-gen.cpp
> +    gpuFPVal = loopB.create<arith::SIToFPOp>(loc, floatType, gpuLoadVal);
Wait a minute, I don't think this is it?
Shouldn't we verify int8 convolution exactly?

2022-02-17 20:38 UTC, krzysz00 commented on mlir/tools/miopen-gen/miopen-gen.cpp
> +    gpuFPVal = loopB.create<arith::SIToFPOp>(loc, floatType, gpuLoadVal);
... which we are doing below, so now the question is - where'd the floating point come from? Shouldn't we add an integer convolution verifier?

2022-02-17 20:39 UTC, jerryyin requested changes
Implementation looks good. I'm putting a blocker for test case. Need at least a couple of small scale e2e test case to make sure i8 testing does what we expect it to do.

2022-02-17 20:43 UTC, yiqian1 commented on mlir/tools/miopen-gen/miopen-gen.cpp
> +    gpuFPVal = loopB.create<arith::SIToFPOp>(loc, floatType, gpuLoadVal);
We're verifying int8 convolution. The int8 results are casted to floating point only for printing.

2022-02-17 20:44 UTC, krzysz00 commented on mlir/tools/miopen-gen/miopen-gen.cpp
> +    gpuFPVal = loopB.create<arith::SIToFPOp>(loc, floatType, gpuLoadVal);
I see `cpuLoadVal` being passed to in integer comparison further down the line though?

2022-02-17 20:45 UTC, krzysz00 commented on mlir/tools/miopen-gen/miopen-gen.cpp
> +    gpuFPVal = loopB.create<arith::SIToFPOp>(loc, floatType, gpuLoadVal);
Ok, so, I'm confused. If we're verifying an int8 convolution, why is the CPU verifier returning floats?

2022-02-17 20:58 UTC, yiqian1 commented on mlir/tools/miopen-gen/miopen-gen.cpp
> +    gpuFPVal = loopB.create<arith::SIToFPOp>(loc, floatType, gpuLoadVal);
Oh, I see what you were asking. The CPU implementation is floating point. The result is casted to integer to compare with the gpu convolution. This should be equivalent to an integer convolution. I feel there is no need to do a cpu integer convolution.

2022-02-17 21:21 UTC, krzysz00 commented on mlir/tools/miopen-gen/miopen-gen.cpp
> +    gpuFPVal = loopB.create<arith::SIToFPOp>(loc, floatType, gpuLoadVal);
Having looked, no, no it's not for output values above 2^24 , per https://stackoverflow.com/questions/3793838/which-is-the-first-integer-that-an-ieee-754-float-is-incapable-of-representing-e

2022-02-17 21:31 UTC, yiqian1 commented on mlir/tools/miopen-gen/miopen-gen.cpp
> +    gpuFPVal = loopB.create<arith::SIToFPOp>(loc, floatType, gpuLoadVal);
You're right. I thought the floating point was safe because I was thinking the output was also int8.

2022-02-23 16:05 UTC, jerryyin commented on mlir/lib/ExecutionEngine/ROCm/rocm-runtime-wrappers.cpp
> +static void getSizesAndStridesInt8(
`getSizesAndStridesInt8()` and `getSizesAndStridesFloat()` are basically copy except argument type therefore needs to be templatized

2022-02-23 16:05 UTC, jerryyin commented on mlir/lib/ExecutionEngine/ROCm/rocm-runtime-wrappers.cpp
> +mcpuConv2dInt8(int64_t rank1, void *f_ptr, int64_t rank2, void *i_ptr,
`mcpuConv2dInt8()` and `mcpuConv2d()` can be templatized on accumulator's type.

2022-02-23 16:05 UTC, jerryyin commented on mlir/lib/ExecutionEngine/ROCm/rocm-runtime-wrappers.cpp
> +extern "C" void mcpuConv2dBwdWeightInt8(
I don't think this is necessary as we only support forward conv for i8

2022-02-23 16:05 UTC, jerryyin commented on mlir/lib/ExecutionEngine/ROCm/rocm-runtime-wrappers.cpp
> +mcpuConv2dBwdDataInt8(int64_t rank1, void *f_ptr, int64_t rank2, void *i_ptr,
I don't think this is necessary as we only support forward conv for i8

2022-02-23 16:05 UTC, jerryyin commented on mlir/tools/miopen-gen/miopen-gen.cpp
> +    //    gpuLoadVal);
Remove those?

2022-02-23 16:05 UTC, jerryyin commented on mlir/tools/miopen-gen/miopen-gen.cpp
> +    gpuFPVal = loopB.create<arith::SIToFPOp>(loc, floatType, gpuLoadVal);
Is this addressed? I still see int to float conversion?

2022-02-24 19:37 UTC, jerryyin approved these changes
LGTM

2022-02-24 21:41 UTC, yiqian1 commented
The old code converted integer results to floating point for printing. The new code directly prints integer results.

2022-02-25 16:10 UTC, merged