MLIR#434: fixed test
ROCm/rocMLIR pull request #550
Opened 2022-03-14 20:38 UTC by sjw36

https://github.com/ROCmSoftwarePlatform/llvm-project-private/issues/434

2022-03-17 20:34 UTC, krzysz00 requested changes
Noting the change request, and since this is on a fork, I can't fix it

2022-03-17 20:34 UTC, krzysz00 commented on mlir/test/fusion/tosa-to-miopen-relu.xmir.mlir
> +// CHECK: func private @resnet50_outlined_part_1(%arg0: memref<1x32x32x64xf32>, %arg1: memref<64x3x3x64xf32>, %arg2: memref<1x32x32x64xf32>, %arg3: memref<1x32x32x64xf32>) attributes {kernel, targets
You ate the `block_size` here.

2022-04-18 16:03 UTC, sjw36 commented on mlir/test/fusion/tosa-to-miopen-relu.xmir.mlir
> +// CHECK: func private @resnet50_outlined_part_1(%arg0: memref<1x32x32x64xf32>, %arg1: memref<64x3x3x64xf32>, %arg2: memref<1x32x32x64xf32>, %arg3: memref<1x32x32x64xf32>) attributes {kernel, targets
fixed, please resolve.

2022-04-19 17:38 UTC, krzysz00 approved these changes

2022-04-19 17:38 UTC, merged