MLIR#468: use miopen.transform instead of memref.expand_shape in TosaToMIOpen
ROCm/rocMLIR pull request #553
Opened 2022-03-15 18:35 UTC by sjw36

Since the conversion of tosa.conv2d will generate an miopen.conv2d which requires 5D tensor parameters, we need to expand the shape of the tosa.conv2d parameters by adding a 'G; dimension of size 1. Currently this is accomplished with a memref.expand_shape operation but this causes problems if we need to insert an miopen.transform<broadcast> for bias-add. The chain of miopen.transforms cannot be broken by memref operations (as currently implemented).

This change will apply only to tosa.conv2d and tosa.matmul operation parameters.

2022-03-15 18:37 UTC, sjw36 commented
This change requires @krzysz00 fix for OOB checks in miopen.transform.

2022-03-18 15:50 UTC, krzysz00 requested changes
I've got significant complaints about how this PR was written.

2022-03-18 15:50 UTC, krzysz00 commented on mlir/include/mlir/Dialect/MIOpen/MIOpen.h
> +  StringRef startName(uint32_t dim);
No, that's not acceptable, since we can't guarantee the lifetime of the returned string within the builder.

2022-03-18 15:50 UTC, krzysz00 commented on mlir/lib/Conversion/TosaToMIOpen/TosaToMIOpen.cpp
> +  SmallVector<StringRef, 8> names{"a", "b", "c", "d", "e", "f", "h", "i"};
... just generate `dim0`, `dim1`, ...

2022-03-18 15:50 UTC, krzysz00 commented on mlir/lib/Dialect/MIOpen/CoordTransformBuilder.cpp
> +void BottomUpCTBuilder::expand(StringRef name, uint32_t dim, int64_t size) {
This isn't a method that goes here

2022-03-18 15:50 UTC, krzysz00 commented on mlir/lib/Dialect/MIOpen/Transforms/AlignTiling.cpp
> +  Value bwTraceTo(Value inp, TransformList *transforms = nullptr) const {
This is `untransform()`

2022-03-18 15:50 UTC, krzysz00 commented on mlir/lib/Dialect/MIOpen/Transforms/AlignTiling.cpp
> +  Value bwTraceTo(Value inp, TransformList *transforms = nullptr) const {
with some extra bits

2022-03-18 15:57 UTC, krzysz00 commented on mlir/lib/Conversion/TosaToMIOpen/TosaToMIOpen.cpp
> +  SmallVector<StringRef, 8> names{"a", "b", "c", "d", "e", "f", "h", "i"};
This violates zero-one-infinity in a very silly way for no good reason

2022-03-18 15:58 UTC, krzysz00 commented on mlir/lib/Dialect/MIOpen/CoordTransformBuilder.cpp
> +void BottomUpCTBuilder::expand(StringRef name, uint32_t dim, int64_t size) {
I mean, maybe it could be, but you're looking for moving `expandNamesInPlace` out of `ConvToGemm` and the top names wrapper

2022-03-18 21:59 UTC, krzysz00 commented on mlir/lib/Dialect/MIOpen/Transforms/AlignTiling.cpp
> +  Value bwTraceTo(Value inp, TransformList *transforms = nullptr) const {
Update: it has somewhat different semantics and so can probably stay its own thing

2022-03-23 19:27 UTC, krzysz00 commented
Closing because #564 went in

2022-03-23 19:27 UTC, closed without merging