[DO NOT SQUASH] Fix fusion test failure by modifying TosaToLinalg.
ROCm/rocMLIR pull request #729
Opened 2022-08-16 08:25 UTC by jungpark-mlir

TosaToLinalg folds its dim first when a dim size of the operands is 1 and add reshape ops later to match with the original shape.
This might complicate the later passes.

For example,
when tosa.add has two compatible tensor operands A[1,30,30,16] and B[1,1,1,16]
TosaToLinalg reshapes B to [16]
and LinalgElementwiseOpFusion pass reshapes A and B to A[1,30,30,1,1,1,16] and B[1,1,1,16] and result also needs to be reshaped from [1,30,30,1,1,1,16] to [1,30,30,16]

This PR prevents TosaToLinalg pass from dropping the dims with size=1 so that the operands of elementwise ops keep their shapes through the converting passes.
Not sure everyone upstream would be happy with this change but this looks more sensible to me (If something need this existing dimension folding, that should be optional)

This also fixes the failed fusion tests.

2022-08-16 09:37 UTC, jungpark-mlir commented
Need to modify the external test as well.

2022-08-16 09:49 UTC, jungpark-mlir commented
Well, 
I need to cover the option to generate the code in the original way so it doesn't break the compatibility in upstream.

2022-08-16 17:23 UTC, krzysz00 requested changes
I don't think this is the right approach either, and I don't want us maintaining this patch on upstream.

Why not have a pass (or a rewrite pattern in an existing pass) somewhere after the linalg elementwise stuff that either replaces the `expand_shape`/`collapse_shape` calls with coordinate transformations? Or something that works the way the rest of our existing broadcast handling does?

Could you also identify upstream commit that causes this problem? (and maybe, in the process, find some sort of flag for restoring the old behavior if we get really lucky)

I think we should meet Thursday or Friday to discuss this at this point.

2022-08-17 04:51 UTC, jungpark-mlir commented
Yeah, I should have checked the history first.

It's not the upstream that introduced folding the dims. The change is only on our repo and was made by @sjw36 in https://github.com/ROCmSoftwarePlatform/llvm-project-mlir/commit/45ecde6aedeb2085abee1785abbd4189be7c7a71

Need to discuss this once he's back.

2022-08-29 17:22 UTC, sjw36 commented
The reason this still fails is that MIOpenLinalgAlign is failing.

2022-08-29 17:39 UTC, jungpark-mlir commented
Yes, I'm reworking this differently now. This needs to be discussed with upstream later.
Closing.

2022-08-29 17:39 UTC, closed without merging