[DO NOT SQUASH] Propagate architecture name throughout the compilation process
ROCm/rocMLIR pull request #807
Opened 2022-10-10 18:28 UTC by krzysz00

1. Rename a lot of "chip" to "arch" to indicate that it's the full
architecture name and not just the chipset
2. Set kernel.arch on the top-level module when generating a single
kernel for compilation
3. Look for kernel.arch when running backend pipelines to avoid system
device lookups
4. Remove the -triple, -target/-chip, and -features options in favor
of -arch
5. In general, when storing the architecture name somewhere,
canonicazize it to triple:chipset:[features how the backend expects
them]
6. Make the sanity tests set a concrete arch value to avoid weird
conflicts.

---

The system devices are no longer a StringMap of chip -> device,
because that's not sufficient to know if a device is usable. Instead,
they now have a vector of pointers into the device lists that were
produced by each detector.

And now there is a find() method that takes a partial architecture
name and reports if we have it on the system.

In addition, features are now stored for all targets as a
StringMap<bool> so we don't have to deal with the varying string
semantics as much.

In unresolved issues that are a @sjw36 @jungpark-mlir : in the MIGraphX flow, where should we be canonicalizing the architecture name?

2022-10-10 20:22 UTC, pcf000 approved these changes
Looks okay to me, but I do see a couple of places where it'll conflict with my current pull request (because I add some RUN lines that'll need to be updated).  Whichever one goes in second will need to update.

Second opinions always welcome.

2022-10-12 17:25 UTC, sjw36 requested changes
Great cleanup. Just keep the cpu attributes and I will unblock.

2022-10-12 17:25 UTC, sjw36 commented on external/llvm-project/mlir/include/mlir/ExecutionEngine/SystemDevices.h
> +class SystemDevices {
Hey, I saw that..

2022-10-12 17:25 UTC, sjw36 commented on external/llvm-project/mlir/include/mlir/ExecutionEngine/SystemDevices.h
> +  find(SystemDevice::Type type, llvm::StringRef partialArchName) const;
The find interface is good, more restrictive but since it is not obvious that the object is always const, this is cleaner.

2022-10-12 17:25 UTC, sjw36 commented on external/llvm-project/mlir/include/mlir/ExecutionEngine/SystemDevices.h
> +  llvm::SmallVector<const SystemDevice *, 0> devices;
Should at least have static size=2 since there will always be a CPU and probably a GPU.

2022-10-12 17:25 UTC, sjw36 commented on external/llvm-project/mlir/include/mlir/ExecutionEngine/SystemDevices.h
> +  llvm::StringMap<bool> features;
Good generalization.

2022-10-12 17:25 UTC, sjw36 commented on external/llvm-project/mlir/lib/ExecutionEngine/CpuSystemDetect.cpp
> -      dev.properties.insert({f.first().str(), val});
I know we aren't using this but let's keep it for now.

2022-10-12 17:25 UTC, sjw36 commented on external/llvm-project/mlir/lib/ExecutionEngine/SystemDevices.cpp
> +    if (matches && !features.empty()) {
What about when features.empty() but device->features is not empty.

2022-10-12 17:25 UTC, sjw36 commented on mlir/lib/CAPI/Dialect/MIGraphX.cpp
> +  opts.indexBitwidth = 32;
@jungpark-mlir please confirm this. I think MIGraphX expects 64 bit for index params.

2022-10-12 17:25 UTC, sjw36 commented on external/llvm-project/mlir/lib/ExecutionEngine/RocmDeviceName.cpp
> +      features, stream,
Is StringMap alphabetical sorted when iterated. May be required in canonical form. https://www.llvm.org/docs/AMDGPUUsage.html#amdgpu-target-id

2022-10-12 17:25 UTC, sjw36 commented on external/llvm-project/mlir/lib/ExecutionEngine/SystemDevices.cpp
> +    if (matches && !features.empty()) {
Looks like when features are not set, the object supports 'any' value. So this does not need to be checked on the device.

2022-10-12 18:04 UTC, krzysz00 commented on external/llvm-project/mlir/include/mlir/ExecutionEngine/SystemDevices.h
> +  llvm::SmallVector<const SystemDevice *, 0> devices;
I went for <0> because that's the common pattern for forcing a heap allocation in SmallVector

2022-10-12 18:05 UTC, krzysz00 commented on external/llvm-project/mlir/lib/ExecutionEngine/CpuSystemDetect.cpp
> -      dev.properties.insert({f.first().str(), val});
... it's in the `features` attribute of the CPU device. So we haven't lost any info.

2022-10-12 18:05 UTC, krzysz00 commented on external/llvm-project/mlir/lib/ExecutionEngine/SystemDevices.cpp
> +    if (matches && !features.empty()) {
Yeah. The check is "if I specified features, then the compiled binary must also have those features with those values"

2022-10-12 18:06 UTC, krzysz00 commented on mlir/lib/CAPI/Dialect/MIGraphX.cpp
> +  opts.indexBitwidth = 32;
Our kernel generation expects index = 32

2022-10-12 18:06 UTC, krzysz00 commented on mlir/lib/CAPI/Dialect/MIGraphX.cpp
> +  opts.indexBitwidth = 32;
and we use it everywhere else. Also, there are no index params

2022-10-12 18:19 UTC, sjw36 commented on external/llvm-project/mlir/lib/ExecutionEngine/CpuSystemDetect.cpp
> -      dev.properties.insert({f.first().str(), val});
Oh, how did I miss that.. makes perfect sense.

2022-10-12 18:21 UTC, sjw36 commented on mlir/lib/CAPI/Dialect/MIGraphX.cpp
> +  opts.indexBitwidth = 32;
what about for memref sizes and strides.

2022-10-12 18:43 UTC, krzysz00 commented on mlir/lib/CAPI/Dialect/MIGraphX.cpp
> +  opts.indexBitwidth = 32;
Bare pointer ABI

2022-10-12 18:43 UTC, krzysz00 commented on mlir/lib/CAPI/Dialect/MIGraphX.cpp
> +  opts.indexBitwidth = 32;
(and yes, we use "index = [u]int32_t" for those inside all our kernels

2022-10-12 18:44 UTC, krzysz00 commented on external/llvm-project/mlir/lib/ExecutionEngine/RocmDeviceName.cpp
> +      features, stream,
Good catch, am fixing

2022-10-13 22:14 UTC, sjw36 commented on mlir/lib/CAPI/Dialect/MIGraphX.cpp
> +  opts.indexBitwidth = 32;
@jungpark-mlir please confirm that this change is correct.

2022-10-14 15:04 UTC, krzysz00 commented on mlir/lib/CAPI/Dialect/MIGraphX.cpp
> +  opts.indexBitwidth = 32;
(For extra context, https://github.com/ROCmSoftwarePlatform/AMDMIGraphX/pull/1333/files, which has landed and is enabled, makes the only parameters to our functions pointers, so this change can't affect the API surface)

2022-10-14 15:28 UTC, sjw36 commented on mlir/lib/CAPI/Dialect/MIGraphX.cpp
> +  opts.indexBitwidth = 32;
Ok, good good.

2022-10-14 15:32 UTC, sjw36 commented on mlir/lib/CAPI/Dialect/MIGraphX.cpp
> +  opts.indexBitwidth = 32;
Do we detect when indexing may overflow on large conv2d? It should cause compile failure.

2022-10-14 15:34 UTC, krzysz00 commented on mlir/lib/CAPI/Dialect/MIGraphX.cpp
> +  opts.indexBitwidth = 32;
We do, but it's currently sitting in `Conv2DGenerator`. I noticed that this morning when Jungwook asked where the check was and have it as a ticket to move it somewhere else, probably on `GemmOp::verify()`

2022-10-14 15:40 UTC, sjw36 commented on mlir/lib/CAPI/Dialect/MIGraphX.cpp
> +  opts.indexBitwidth = 32;
Sounds good.

2022-10-14 15:41 UTC, sjw36 approved these changes
Approving with follow-up ticket to detect when index overflows.

2022-10-14 15:43 UTC, merged